// Generated by CoffeeScript 1.4.0
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['jquery', 'backbone', 'application/views/mainView', 'application/models/app'], function($, Backbone, MainView, App) {
  var Router;
  return Router = (function(_super) {

    __extends(Router, _super);

    Router.prototype.routes = {
      'organisation': 'organisationScreen',
      'conference/:orgid': 'conferenceScreen',
      'slides/:confid': 'slideScreen',
      '*actions': 'organisationScreen'
    };

    function Router(socket) {
      this.socket = socket;
      Router.__super__.constructor.call(this, this.routes);
    }

    Router.prototype.initialize = function() {
      this.trigger('orgRoute');
      this.app = new App();
      this.mainView = new MainView({
        model: this.app
      });
      Backbone.history.start();
      return console.log(" The Route Initialized");
    };

    Router.prototype.organisationScreen = function() {
      $('.slides').fadeOut();
      $('.confBlock').removeClass('onshow');
      return $('.organisationsBlock').addClass('onshow');
    };

    Router.prototype.conferenceScreen = function(orgid) {
      console.log("emmission choosed");
      /*$('.organisationsBlock').removeClass('onshow')
      $('.confBlock').show ()->
        $('.confBlock').addClass('onshow')
      */

      return this.socket.emit('organisationChoosed', orgid);
      /*@trigger 'confRoute', orgid
      $('.slides').fadeOut ()->
        $('.confBlock').fadeIn()
      */

    };

    Router.prototype.slideScreen = function(confid) {
      this.trigger('slideRoute', confid);
      return $('.confBlock').fadeOut(function() {
        return $('.slides').fadeIn();
      });
    };

    return Router;

  })(Backbone.Router);
});
