// Generated by CoffeeScript 1.5.0
var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

define(['jquery', 'backbone'], function($, Backbone) {
  var Carousel;
  return Carousel = (function() {

    function Carousel(element) {
      this.handleHammer = __bind(this.handleHammer, this);      this.elt = $(element);
      console.log(element);
      console.log(this.elt);
      this.tempcontainer = element + " > ul";
      this.templi = element + " > ul  li";
      this.tempcurrent = element + " li.current";
      this.currentSlide = $(this.tempcurrent);
      console.log(this.currentSlide);
      this.width = this.currentSlide.width();
      this.container = $(this.tempcontainer);
      this.slides = $(this.templi);
      this.current = 0;
      this.count = 1;
    }

    Carousel.prototype.init = function() {
      return this.elt.hammer({
        drag_lock_to_axis: true
      }).on("release dragleft dragright swipeleft swiperight", this.handleHammer);
    };

    Carousel.prototype.handleHammer = function(ev) {
      var pane_width, strpx;
      console.log(ev.gesture.deltaX);
      ev.gesture.preventDefault();
      switch (ev.type) {
        case 'dragright':
          strpx = ev.gesture.deltaX + "px";
          return $(this.tempcurrent).css("margin-left", strpx);
        case 'dragleft':
          strpx = ev.gesture.deltaX + "px";
          return $(this.tempcurrent).css("margin-left", strpx);
        case 'swipeleft':
          $('#suivant').click();
          ev.gesture.stopDetect();
          return $(this.tempcurrent).attr('style', ' ');
        case 'swiperight':
          $('#precedent').click();
          ev.gesture.stopDetect();
          return $(this.tempcurrent).attr('style', ' ');
        case 'release':
          pane_width = $(this.tempcurrent).width();
          if (Math.abs(ev.gesture.deltaX) > pane_width / 3) {
            $('#suivant').click();
            ev.gesture.stopDetect();
          } else {
            $('#precedent').click();
            ev.gesture.stopDetect();
          }
          return $(this.tempcurrent).attr('style', ' ');
      }
    };

    return Carousel;

  })();
});
