// Generated by CoffeeScript 1.4.0
var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

define(['jquery', 'backbone', 'modernizr'], function($, Backbone, Modernizr) {
  var Carousel;
  return Carousel = (function() {

    function Carousel(element) {
      this.handleHammer = __bind(this.handleHammer, this);
      console.log(Modernizr);
      this.elt = $(element);
      console.log(element);
      console.log(this.elt);
      this.tempcontainer = element + " > ul";
      this.templi = element + " > ul  li";
      this.tempcurrent = element + " li.current";
      this.currentSlide = $(this.tempcurrent);
      console.log(this.currentSlide);
      this.width = this.currentSlide.width();
      this.container = $(this.tempcontainer);
      this.slides = $(this.templi);
      this.current = 0;
      this.count = 1;
    }

    Carousel.prototype.init = function() {
      return this.elt.hammer({
        drag_lock_to_axis: true
      }).on("release dragleft dragright swipeleft swiperight", this.handleHammer);
    };

    Carousel.prototype.stick = function(percent, deltaX) {
      /*if Modernizr.csstransforms3d 
        $(@tempcurrent).css("transform", "translate3d("+percent+"%,0,0) scale3d(1,1,1)");
          
      else if Modernizr.csstransforms
        $(@tempcurrent).css("transform", "translate("+percent+"%,0)")
          
      else
      */
      return $(this.tempcurrent).css("left", deltaX);
    };

    Carousel.prototype.handleHammer = function(ev) {
      var pane_width, percent, strpx, taille;
      ev.gesture.preventDefault();
      switch (ev.type) {
        case 'dragright':
          console.log($(this.tempcurrent).css('left'));
          console.log($(this.tempcurrent).css('margin-left'));
          taille = parseInt($("#appcontainer").width());
          percent = (ev.gesture.deltaX / taille) * 100;
          strpx = ev.gesture.deltaX + "px";
          return this.stick(percent, strpx);
        case 'dragleft':
          console.log($(this.tempcurrent).css('left'));
          console.log($(this.tempcurrent).css('margin-left'));
          taille = parseInt($("#appcontainer").width());
          percent = (ev.gesture.deltaX / taille) * 100;
          strpx = ev.gesture.deltaX + "px";
          return this.stick(percent, strpx);
        case 'swipeleft':
          $('#suivant').click();
          ev.gesture.stopDetect();
          return $(this.tempcurrent).css('left', '0px');
        case 'swiperight':
          $('#precedent').click();
          ev.gesture.stopDetect();
          return $(this.tempcurrent).css('left', '0px');
        case 'release':
          pane_width = $(this.tempcurrent).width();
          if (Math.abs(ev.gesture.deltaX) > pane_width / 2) {
            $('#suivant').click();
            return ev.gesture.stopDetect();
          } else {
            $('#precedent').click();
            return ev.gesture.stopDetect();
          }
      }
    };

    return Carousel;

  })();
});
