// Generated by CoffeeScript 1.5.0
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['jquery', 'backbone', 'application/views/organisationView', 'application/views/carousel'], function($, Backbone, OrganisationView, Carousel) {
  var mainView;
  return mainView = (function(_super) {

    __extends(mainView, _super);

    function mainView() {
      mainView.__super__.constructor.apply(this, arguments);
    }

    mainView.prototype.el = '#header';

    mainView.prototype.initialize = function() {
      var lastTime, vendors, x,
        _this = this;
      this.listenTo(this.model, 'change:organisations', this.render);
      this.listenTo(this.model, 'home', this.emptyConfs);
      $('#prevpage').hide();
      this.offset = 0;
      this.on('ServerConnection', function(data) {
        console.log("mainV connected");
        return _this.connectNotif(data);
      });
      $('#appcontainer').delegate('#nextpage', 'click', function(e) {
        return _this.nextPage();
      });
      $('#appcontainer').delegate('#prevpage', 'click', function(e) {
        return _this.prevPage();
      });
      $('#header').delegate('#all-shows', 'click', function(e) {
        return _this.allShows();
      });
      /*$('#prevpage').waypoint 
        handler:() =>
          console.log "waypoint"
        offset: '-100%'
      
      $('#nextpage').waypoint
        handler:() =>
          console.log "waypointnext"
        offset: '100%'
      */

      $('#appcontainer').scroll(function() {
        console.log("scroll");
        if ($("#nextpage").offset().top + $("#nextpage").outerHeight() === $('#appcontainer').height() && _this.model.allLoaded) {
          return $("#nextpage").click();
        }
      });
      /* $('#appcontainer').delegate '.conf-item' ,'click ', (e)=>
        txt = $(e.target).attr('id')
        @model.get('organisation').conferenceChoosed txt
        @trigger 'conferenceChoosed', txt
      */

      $('#suivant').click(function(e) {
        e.preventDefault();
        return _this.model.trigger("next");
      });
      $('#precedent').click(function(e) {
        e.preventDefault();
        return _this.model.trigger("previous");
      });
      lastTime = 0;
      vendors = ["ms", "moz", "webkit", "o"];
      x = 0;
      while (x < vendors.length && !window.requestAnimationFrame) {
        window.requestAnimationFrame = window[vendors[x] + "RequestAnimationFrame"];
        window.cancelAnimationFrame = window[vendors[x] + "CancelAnimationFrame"] || window[vendors[x] + "CancelRequestAnimationFrame"];
        ++x;
      }
      if (!window.requestAnimationFrame) {
        window.requestAnimationFrame = function(callback, element) {
          var currTime, id, timeToCall;
          currTime = new Date().getTime();
          timeToCall = Math.max(0, 16 - (currTime - lastTime));
          id = window.setTimeout(function() {
            return callback(currTime + timeToCall);
          }, timeToCall);
          lastTime = currTime + timeToCall;
          return id;
        };
      }
      if (!window.cancelAnimationFrame) {
        window.cancelAnimationFrame = function(id) {
          return clearTimeout(id);
        };
      }
      this.carousel = new Carousel(".slides");
      return this.carousel.init();
    };

    mainView.prototype.connectNotif = function(data) {
      console.log("notif connected");
      return $('.label').slideUp(function() {
        console.log('first');
        $('.label').removeClass('label-important').addClass('label-success');
        $('.label').text('connected');
        console.log("seconde");
        return $('.label').slideDown();
      });
    };

    mainView.prototype.render = function() {
      $('.organisation').remove();
      console.log("main view is redenring");
      this.model.get('organisations').each(function(organisation) {
        var organisationView;
        organisationView = new OrganisationView({
          model: organisation
        });
        return $('.dropdown-menu').append(organisationView.render().el);
      });
      $('.emissions').text($('#all-shows').text());
      $("#loading").fadeOut();
      $("#wrap").fadeIn();
      return $("#header").fadeIn();
    };

    mainView.prototype.emptyConfs = function() {
      console.log("got to empty home");
      return $('.conference').remove();
    };

    mainView.prototype.nextPage = function() {
      var href, orgid, page;
      if (typeof this.model.get('orgChoose') === 'undefined') {
        page = this.model.get('page');
        page = page + 1;
        href = 'all/' + page;
        Backbone.history.navigate(href, {
          trigger: true
        });
        return console.log('nextPage');
      } else {
        if (this.model.get('orgChoose') === ' ') {
          page = this.model.get('page');
          page = page + 1;
          href = 'all/' + page;
          Backbone.history.navigate(href, {
            trigger: true
          });
          return console.log(href);
        } else {
          page = this.model.get('organisations').get(this.model.get('orgChoose')).get('page');
          page = page + 1;
          orgid = this.model.get('orgChoose');
          href = 'conference/' + orgid + '/' + page;
          Backbone.history.navigate(href, {
            trigger: true
          });
          return console.log(href);
        }
      }
    };

    mainView.prototype.prevPage = function() {};

    mainView.prototype.allShows = function() {
      $('.emissions').text($('#all-shows').text());
      return Backbone.history.navigate('home/', {
        trigger: true
      });
    };

    return mainView;

  })(Backbone.View);
});
