// Generated by CoffeeScript 1.5.0

requirejs.config({
  paths: {
    jquery: 'vendors/jquery/jquery',
    underscore: 'vendors/underscore/underscore',
    backbone: 'vendors/backbone/backbone',
    backbonels: 'vendors/backbone/backbone.localStorage',
    bootstrap: 'vendors/bootstrap/bootstrap',
    waypoints: 'vendors/jquery/waypoints',
    infinitescroll: 'vendors/jquery/infinitescroll',
    hammer: 'vendors/hammer/hammer',
    text: 'vendors/require/text'
  },
  shim: {
    backbone: {
      deps: ['jquery', 'underscore'],
      exports: 'Backbone'
    },
    underscore: {
      exports: '_'
    },
    bootstrap: {
      deps: ['jquery']
    },
    waypoints: {
      deps: ['jquery']
    },
    infinitescroll: {
      deps: ['jquery']
    },
    hammer: {
      deps: ['jquery']
    }
  },
  wait: '5s'
});

require(['backbone', 'backbonels', 'jquery', 'application/models/application', 'bootstrap', 'waypoints', 'infinitescroll', 'hammer'], function(Backbone, Backbonels, $, App, Bs, Wp, Is, Hm) {
  return $(function() {
    App = new App();
    return console.log("launched");
  });
});
